version: '3'

services:
  django-auth-template:
    build:
      context: .
      args:
        UID: $UID
      # Enable this if your image is deployed to a cotainer registry
      # cache_from: 
      #   - path-to-image-in-container-registry:latest
    container_name: django-auth-template
    image: django-auth-template
    command: ./.docker/entrypoint.sh
    volumes:
      - static-data:/vol/web
      - .:/home/python/app
    ports:
      - 8000:8000
    depends_on:
      - db-auth-template

  db-auth-template:
    image: postgres:11-alpine
    container_name: db-auth-template
    environment:
      - POSTGRES_DB=django-auth-template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  static-data:


